name: paseos_mascotas
description: "A new Flutter project."

# Evita publicar accidentalmente en pub.dev
publish_to: 'none'

# Versión de la aplicación
version: 1.0.0+1

# Entorno de desarrollo
environment:
  sdk: ">=3.0.0 <4.0.0"

# Dependencias
dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.11.0
  cloud_firestore: ^5.6.3
  geolocator: ^13.0.2
  stripe_sdk: ^5.0.0
  google_maps_flutter: ^2.10.0
  animated_text_kit: ^4.2.3
  firebase_auth: ^5.0.0
  flutter_facebook_auth: ^7.1.1
  google_sign_in: ^6.1.0  # Para autenticación con Google (opcional)
  intl: ^0.20.2

# Dependencias de desarrollo
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0  # Lints recomendados para Flutter

# Configuración específica de Flutter
flutter:
  uses-material-design: true  # Incluye los iconos de Material Design
  assets:
    - assets/images/mascota1.jpeg
    - assets/images/mascota2.jpeg
