name: paseos_mascotas
description: Aplicación para paseos de mascotas

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.1
  provider: ^6.1.1
  firebase_core: ^3.12.1
  firebase_auth: ^5.0.2
  flutter_facebook_auth: ^7.1.1
  cloud_firestore: ^5.6.5
  google_sign_in: ^6.2.1  # ← Agregado aquí
  google_maps_flutter: ^2.11.0
  geolocator: ^11.0.0
  geocoding: ^3.0.0
  intl: ^0.19.0
  palette_generator: ^0.3.3+6
  animated_text_kit: ^4.2.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/login_background.jpg
    - assets/images/marker.png
    - assets/images/dos_perros_corriendo_en_zona_verde_de.jpeg
    - assets/images/facebook_icon.png
    - assets/images/google_icon.png
    - assets/images/paseador_con_tres_perros_en_un_parque.mp4

