// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWgNKkByd7LgcjueIKETkW2KMaMjkLwEc',
    appId: '1:548551285958:web:d6dee3d244d13de1d64bc7',
    messagingSenderId: '548551285958',
    projectId: 'paseos-de-mascotas',
    authDomain: 'paseos-de-mascotas.firebaseapp.com',
    storageBucket: 'paseos-de-mascotas.firebasestorage.app',
    measurementId: 'G-1NF9J0H2QQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-S5a8jb6S0CqI6rCmBoCSt4vbM3TjrGQ',
    appId: '1:548551285958:android:84164d6a0ef22bb7d64bc7',
    messagingSenderId: '548551285958',
    projectId: 'paseos-de-mascotas',
    storageBucket: 'paseos-de-mascotas.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpFZpF2mBp6YFe1dTJ3AIeU0D4Xi0Z8Ys',
    appId: '1:548551285958:ios:86c441975f20d04bd64bc7',
    messagingSenderId: '548551285958',
    projectId: 'paseos-de-mascotas',
    storageBucket: 'paseos-de-mascotas.firebasestorage.app',
    iosBundleId: 'com.example.paseosMascotas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpFZpF2mBp6YFe1dTJ3AIeU0D4Xi0Z8Ys',
    appId: '1:548551285958:ios:86c441975f20d04bd64bc7',
    messagingSenderId: '548551285958',
    projectId: 'paseos-de-mascotas',
    storageBucket: 'paseos-de-mascotas.firebasestorage.app',
    iosBundleId: 'com.example.paseosMascotas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWgNKkByd7LgcjueIKETkW2KMaMjkLwEc',
    appId: '1:548551285958:web:6d8d675a711d8979d64bc7',
    messagingSenderId: '548551285958',
    projectId: 'paseos-de-mascotas',
    authDomain: 'paseos-de-mascotas.firebaseapp.com',
    storageBucket: 'paseos-de-mascotas.firebasestorage.app',
    measurementId: 'G-4R31LWZ683',
  );
}
